fixed_frame: world
predicate_options:
    "fov":
        target_frame: /camera_rgb_optical_frame
        minimum_distance_from_camera: 0.20
        maximum_fov_angle: 0.50614505555
        maximum_fov_angle_vertical: 0.6108647222
    "on_table":
        table_start:
            x:  0.349411
            y: -0.928208
            z: -0.151894
        table_end:
            x:  1.056246
            y:  0.627350
            z: -0.200051
    "on":
        upper_limit_multiplier: 0.1
        lower_limit_multiplier: 0.45
input_source_options:
    "Segmentation":
        min_cloud_intersection: 0.12
        confidence_confusion_matrix: [0.9, 0.1, 0.45, 0.55]
        location_pdf_sigma_matrix: [0.001, 0, 0, 0, 0.001, 0, 0, 0, 0.001]
